### ISSUE TITLE
Standardize log formatting

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#168] opened 2021-10-28 19:36 UTC
Standardize the output for logs. Fixed column width. 

`LEVEL TIMESTAMP  WHAT_HAPPENED   FIELD_A=VALUE_A FIELD_B=VALUE_B`

I've spent some time digging into this, initially I was using [env_logger](https://docs.rs/env_logger/0.9.0/env_logger/) to standardize the output formatting. Not too difficult to format / enforce column width on `LEVEL` & `TIMESTAMP`, but has some restrictions - the "message" field is available only as a [string](https://docs.rs/log/0.4.14/log/struct.Record.html#method.args). Which means that any formatting/width restrictions need to be standardized and enforced on an individual bases in the `Display` implementation as @jacobkaufmann [suggested](https://github.com/ethereum/trin/pull/158#issuecomment-952151548). 

Also, using `env_logger` introduced some conflicts with our current state of using both the `log` crate and the `tracing` crate to capture/output logs. If I understand correctly, `env_logger` isn't compatible with traces. And best practice is to use [one or the other](https://www.lpalmieri.com/posts/2020-09-27-zero-to-production-4-are-we-observable-yet/#5-2-migrating-from-log-to-tracing). 

Do we want to migrate to use `tracing` exclusively? @lithp I believe you've the most experience with implementing `tracing` in this library so far - thoughts?

**Comment by lithp** [comment] 2021-10-30 04:25
I believe this was an accidental close, correct me if I'm wrong!

I have very little experience with `tracing` but it seems quite useful, by adding spans we can remember which context each function is being called in, and print some details of our context whenever we emit logs. 

`tracing` should still allow us to standardize our output formats, it should be possible to write a custom [`Layer`](https://docs.rs/tracing-subscriber/0.2.12/tracing_subscriber/layer/trait.Layer.html).

**Comment by carver** [comment] 2021-11-03 16:57
I think this is a duplicate of #167 ?

**Closed by carver** 2021-11-03 16:57 UTC
