### ISSUE TITLE
Deprecate native NodeId implementation

### ISSUE THREAD

**Issue by njgheorghita** [ethereum/trin#869] opened 2023-08-26 00:23 UTC
Remove the [native type implementation](https://github.com/ethereum/trin/blob/da85728e5e38916ba8eddf6e5e97201d70d88a91/ethportal-api/src/types/node_id.rs#L29), and replace all usage with the equivalent type from the [discv5 crate](https://github.com/sigp/discv5).

- [ ] Make sure that all of our `portal_*traceRecursiveFindContent` jsonrpc api endpoints correctly ser/de the response
- [ ] Run it against [portal-hive](https://github.com/ethereum/portal-hive)

**Comment by morph-dev** [comment] 2023-10-18 19:33
I looked into this issue, and here are my findings.

We can't just simply change to `discv5::enr::NodeId`. The reason is that deserializing `NodeId` from `serde_json::Value` fails.

I created the issue with minimal test to reproduce and a way to fix it in the original project: https://github.com/sigp/enr/issues/62

We would have to wait for [enr crate](https://github.com/sigp/enr) to fix it, push new version, for [discv5 crate](https://github.com/sigp/discv5) to upgrade deps and push new version. And than we can upgrade and remove our version.

Alternatively, maybe in our code we can avoid using `serde_json::Value` (and use String instead), or serialize it to `String` before deserializing.

**Comment by KolbyML** [comment] 2023-10-18 21:10
Waiting for the enr crate wouldn't be a problem. Normally my goto is to just make a PR on sigp/enr with your fix, as that normally resolves the issue faster then making an issue and don't be afraid to ping the maintainers for review. Good investigating :monocle_face:

**Comment by morph-dev** [comment] 2023-12-01 16:58
The PR that updates the `enr` dependency in `discv5` repo is merged.

I just now noticed that we actually don't use their release version. Instead we use this one: https://github.com/njgheorghita/discv5. I don't know why we depend on it and not the official release version (I assume we have some custom changes).

@njgheorghita, what would be the best way to proceed?

**Comment by KolbyML** [comment] 2023-12-01 17:00
@morph-dev we are using the branch version right now since Nick's concurrent PR isn't merged yet on sigp/discv5. Once that is done we will switch back to using sigp/discv5 instead of nick/discv5

**Comment by njgheorghita** [comment] 2023-12-12 15:32
@morph-dev I believe this is unblocked for you after #1067 gets merged

**Closed** 2023-12-14 20:37 UTC
Labels: good-first-issue
