### ISSUE TITLE
test_response_to_triple_ack local test failure

### ISSUE THREAD

**Issue by carver** [ethereum/trin#286] opened 2022-03-31 22:44 UTC
Repeatable test failure (3 of 3 attempts on a fresh checkout of master at c00e99c6b

CI appears green at the commit, so I'm guessing it's some kind of configuration issue. I just added here for tracking (and also a reminder to add a README section about running the local test).

Captured output:
```
$ TRIN_INFURA_PROJECT_ID=1 RUST_LOG=debug cargo test -p trin-core
    Finished test [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests (target/debug/deps/trin_core-19ec7be1499b1d43)

running 127 tests
test cli::test::test_custom_discovery_port ... ok
✂️ ✂️ ✂️ 
test portalnet::types::content_key::test::test_distance_to_key ... ok
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up RocksDB at path: "/tmp/trin.8RiPOGjQik5o/rocksdb"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up SqliteDB at path: "/tmp/trin.8RiPOGjQik5o/trin.sqlite"
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Discv5 service already shutdown
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Discv5 service already shutdown
test utp::stream::tests::test_response_to_triple_ack ... FAILED
test portalnet::types::content_key::test::test_should_store ... ok
[2022-03-31T22:40:03Z INFO  trin_core::portalnet::discovery] Starting discv5 with local enr encoded=enr:-IS4QJIjtY6mIYt5tnOIa89gnMsZu76Bd5Bg45gMaUKJW-RoAHq6nMg0r4G4APtTTduRlnekuWgp9QKyZKnIt78zBfsBgmlkgnY0gmlwhMCoAcCJc2VjcDI1NmsxoQJ9TpUJQOxBIiqmFdLWSXi81LLm9HrWkpwH_JTIaQuhU4N1ZHCCEJI decoded=ENR: NodeId: 0x5b61..bb5f, Socket: Some(192.168.1.192:4242)
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up RocksDB at path: "/tmp/trin.8RiPOGjQik5o/rocksdb"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::storage] Setting up SqliteDB at path: "/tmp/trin.8RiPOGjQik5o/trin.sqlite"
[2022-03-31T22:40:03Z DEBUG trin_core::portalnet::overlay_service] [History] Sending Ping request to node. Node: 0x08d3..fb5a
[2022-03-31T22:40:03Z DEBUG discv5::discv5] Service is already shutdown
test portalnet::overlay_service::tests::ping_node ... ok

failures:

---- utp::stream::tests::test_response_to_triple_ack stdout ----
thread 'utp::stream::tests::test_response_to_triple_ack' panicked at 'called `Result::unwrap()` on an `Err` value: Discv5 socket timeout', trin-core/src/utp/stream.rs:1623:37


failures:
    utp::stream::tests::test_response_to_triple_ack

test result: FAILED. 126 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.24s
```

**Comment by ogenev** [comment] 2022-04-01 08:22
Hmm, this is weird. I just tested it on a brand new laptop under Ubuntu and it pass all tests on multiple runs without any additional configurations. 

@carver could you check please if you get the same issue with https://github.com/ethereum/trin/pull/283?

**Comment by ogenev** [comment] 2022-04-05 14:55
Suddenly, I also started to experience the same issue on my laptop, so I dig a little bit more.

On my side, the problem was related to discv5 packet timeout because of this warning:

```js
Apr 05 16:58:48.782  WARN discv5::handler: Session has invalid ENR. Enr socket: Some(192.168.100.50:9601), Node: 0xe41d..8629, addr: 192.168.100.61:9601
```

As we can see, there is some discrepancy between the Enr socket from the packet and the Node addr .

It looks like the issue is related to network interfaces, when we have more than one up and running interface, as this example:

```sh
ogenev:eth/ $ ifconfig -a                                                                                                            
enx349971e17709: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.61  netmask 255.255.255.0  broadcast 192.168.100.255
         .....

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        ....

wlo1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.50  netmask 255.255.255.0  broadcast 192.168.100.255
        ...
```

This is because my machine was simultaneously running ethernet and wireless interfaces and when we pass `--internal-ip` flag
we always assign the first active interface IP address to discv5 but it seems discv5 is expecting the node address to be my wlan interface:

https://github.com/ethereum/trin/blob/fb5c3ed3542d0cda9aa0eb3a8f269be1ba0b3251/trin-core/src/socket.rs#L47

Not sure how we should deal with this, for now, for an appropriate fix, probably we should dig more into discv5 code to see how exactly the ENR socket address is created when sending auth challenge to a remote node

if we close one of the interfaces, there are no issues.

**Comment by carver** [comment] 2022-04-07 19:42
Weird, I thought the plan was that ENRs make a best effort to know their own IP, but that we don't *reject* a node for having a mismatch IP (for example, if they're behind a NAT).

For reference, here is where discv5 is enforcing that rule:
https://github.com/sigp/discv5/blob/506c9afe6a037dc3ba920f691068dac29f6cba7c/src/handler/mod.rs#L769

Interestingly, the test failures are random, as of e876d5b77b4. It also includes the tests `trin-core/tests/overlay` and `test_duplicate_packet_handling`:

```
thread 'overlay' panicked at 'Unable to respond to ping: The request timed out', trin-core/tests/overlay.rs:156:21
```

and

```
---- utp::stream::tests::test_duplicate_packet_handling stdout ----
thread 'utp::stream::tests::test_duplicate_packet_handling' panicked at 'assertion failed: `(left == right)`
  left: `SynSent`,
 right: `Connected`', trin-core/src/utp/stream.rs:1786:9
```

I'll keep poking around...

**Comment by carver** [comment] 2022-04-12 22:06
This seems most easily reproducible in `trin-core/tests/overlay.rs`, probably because it launches 3 nodes, so there are more opportunities for the IP to shift.

To add to @ogenev 's point: we always pick the "first" NIC, but the order that NICs are returned is unstable, even within the same test. So if the list of non-loopback NICs is longer than 1, then we launch with a random IP. In the overlay test above, there's a 75% chance that one of the 3 nodes has a different IP from the others. (This failure rate is observed roughly in my local runs)

My understanding here is that the problem is that when we *send* the data, we don't define an IP address. I believe the OS chooses that for us. So if we are sending from one local IP to another, the OS will (helpfully) choose to send from the same IP as the recipient IP. But then it won't match the chosen IP for the ENR.

But... whatever the reason, I believe that the data coming from a different IP shouldn't blow up the connection. If a peer misidentifies its IP in the ENR, we should just reply back with the IP we see and carry on, right? I thought that was in place to accommodate NAT traversal issues.

So we could go about trying to line up the IPs, but I'm currently more interested in adding resilience when the sending IP doesn't match the ENR.

**Comment by carver** [comment] 2022-04-12 22:34
> r, I believe that the data coming from a different IP shouldn't blow up the connection. If a peer misidentifies its IP in the ENR, we should just reply back with the IP we see and carry on, right? I thought that was in place to accommodate NAT traversal issues.

If I'm wrong about this ^ then there are other paths to resolving this. Some options:

1. Currently, the sending IP is set with the same IP as the listen IP. If discv5 is meant to be strict about ENR IPs, then it would be reasonable to change discv5 to listen on 0.0.0.0, but send with the same IP as the ENR.
2. If that becomes a black hole, we could just configure the node to both listen and send from the ENR IP.

**Comment by carver** [comment] 2022-04-13 22:56
So I've been able to verify locally that this patch prevents the overlay error across 5 consecutive runs:
```diff
diff --git a/src/handler/mod.rs b/src/handler/mod.rs
index 2aebd31..5a7769a 100644
--- a/src/handler/mod.rs
+++ b/src/handler/mod.rs
@@ -750,10 +750,8 @@ impl Handler {
     /// Verifies a Node ENR to it's observed address. If it fails, any associated session is also
     /// considered failed. If it succeeds, we notify the application.
     fn verify_enr(&self, enr: &Enr, node_address: &NodeAddress) -> bool {
-        // If the ENR does not match the observed IP addresses, we consider the Session
-        // failed.
+        // Verify the node public key (address) matches
         enr.node_id() == node_address.node_id
-            && (enr.udp_socket().is_none() || enr.udp_socket() == Some(node_address.socket_addr))
     }
 
     /// Handle a message that contains an authentication header.
```

This is almost certainly *too* lax, since it would add the ENR to the routing tables, and propagate it to other peers, even if the IP is unreachable. But it's nice to know that the change is sufficient.

**Comment by ogenev** [comment] 2022-04-14 12:09
> To add to @ogenev 's point: we always pick the "first" NIC, but the order that NICs are returned is unstable, even within the same test. So if the list of non-loopback NICs is longer than 1, then we launch with a random IP. In the overlay test above, there's a 75% chance that one of the 3 nodes has a different IP from >=1 of the others. (This failure rate is observed roughly in my local runs

Is there a way to make that returned NICs stable? I think when the OS decides which NIC to use, it is looking at the IP routing table:

```s
$ route -n                                                                                                 [14:51:19]
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.100.1   0.0.0.0         UG    100    0        0 enx349971e17709
0.0.0.0         192.168.100.1   0.0.0.0         UG    600    0        0 wlo1
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 wlo1
192.168.100.0   0.0.0.0         255.255.255.0   U     100    0        0 enx349971e17709
192.168.100.0   0.0.0.0         255.255.255.0   U     600    0        0 wlo1
```
When we have two interfaces pointing to the default route (0.0.0.0) as above, I **assume** it is always choosing the NIC with the lowest "Metric" value. So maybe if we can access this table in rust, get the interface with the lowest metric, and then lookup the NIC IP it should make this more stable?

**Comment by carver** [comment] 2022-04-14 19:30
> Is there a way to make that returned NICs stable?

Yeah, this does seem possible, but I'm not sure it's worth prioritizing. As soon as we modify discv5 to accept connections from mismatched IPs, the NIC instability will be moot. It's actually kind of nice that the instability highlighted the bigger problem that discv5 is too strict.

**Comment by carver** [comment] 2022-04-14 20:52
So I believe I have the main thrust of the change in this PR: https://github.com/sigp/discv5/pull/109 . We'll see what sigp thinks...

**Comment by jacobkaufmann** [comment] 2022-08-03 18:14
Reopening as this failure surfaced again recently (noted in #377).

**Comment by njgheorghita** [comment] 2023-08-24 19:10
closing since this bug hasn't been reported in over a year

**Closed by njgheorghita** 2023-08-24 19:10 UTC
