### ISSUE TITLE
panic caused by IPC

### ISSUE THREAD

**Issue by carver** [ethereum/trin#183] opened 2021-11-15 22:08 UTC
A web3 client should not be able to panic trin. Did this somehow.
```
thread 'thread panicked while processing panic. aborting.
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', trin-core/src/jsonrpc/service.rs:161:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Illegal instruction (core dumped)
```

Still have a TODO to reproduce, but I think I was basically reconnecting a bunch of times. Like in python, I had a `w3 = Web3(Web3.IPCProvider("/tmp/trin-jsonrpc.ipc"))` and then ran the same line again exactly. Was also running ethportal-peertest against the same trin client.

---

Unfortunately, I wasn't able to reproduce this using the above plan. It may be some complicated mix of running a couple of times, maybe across my laptop going standby.

**Comment by njgheorghita** [comment] 2023-08-24 18:39
closing as this is quite old, and hasn't been a recurring panic. most likely due to the fact that we've switched to using a library for ipc report which is much more resilient than our prior, in-house ipc server which was likely the cause of this panic

**Closed by njgheorghita** 2023-08-24 18:39 UTC
