### ISSUE TITLE
Cleaner handling of Ctrl-C

### ISSUE THREAD

**Issue by carver** [ethereum/trin#389] opened 2022-07-28 15:54 UTC
Our current move is to `exit(1)` after getting a Ctrl-C.

In the wise words of @SamWilsn:
> `std::process::exit(1)` is a wonderful way to shut down uncleanly

This chapter seems to have some good suggestions for doing something more cleanly: https://rust-cli.github.io/book/in-depth/signals.html

**Comment by SamWilsn** [comment] 2022-07-28 16:10
Looks like trin is still tokio-based, so I'd probably recommend using [`tokio::signal::ctrl_c`](https://docs.rs/tokio/latest/tokio/signal/fn.ctrl_c.html) to catch the signal. I've had some luck using [`tokio::sync::broadcast`](https://docs.rs/tokio/1.20.1/tokio/sync/broadcast/index.html) to trigger a graceful shutdown, though it generally means weaving `broadcast::Receiver` into every stream and IO operation.

See https://tokio.rs/tokio/topics/shutdown.

**Comment by ogenev** [comment] 2022-07-28 16:18
> Our current move is to `exit(1)` after getting a Ctrl-C.

I thought we are using `exit(1`) only on the jsonrpc server, the main process is handled by [tokio::signal::ctrl_c](https://github.com/ethereum/trin/blob/ae4423ce755f1ce89843b6d6a17aaa6ededdba34/src/main.rs#L16).

**Comment by carver** [comment] 2022-07-28 16:21
Right, the ones I found are here:

https://github.com/ethereum/trin/blob/ae4423ce755f1ce89843b6d6a17aaa6ededdba34/trin-core/src/jsonrpc/service.rs#L186-L195

https://github.com/ethereum/trin/blob/ae4423ce755f1ce89843b6d6a17aaa6ededdba34/trin-core/src/jsonrpc/service.rs#L82-L109

**Comment by carver** [comment] 2022-07-28 16:22
> I thought we are using `exit(1`) only on the jsonrpc server, the main process is handled by [tokio::signal::ctrl_c](https://github.com/ethereum/trin/blob/ae4423ce755f1ce89843b6d6a17aaa6ededdba34/src/main.rs#L16).

Still a problem in the json-rpc server though, right?

**Comment by ogenev** [comment] 2022-07-28 16:33
Yes, I mean the problem is in handling `ctrl_c` in the json-rpc server which doesn't make sense because the main tokio thread is handled already in `main.rs` with [tokio::signal::ctrl_c](https://github.com/ethereum/trin/blob/ae4423ce755f1ce89843b6d6a17aaa6ededdba34/src/main.rs#L16).

**Comment by KolbyML** [comment] 2023-04-16 17:45
If we are no longer https://github.com/ethereum/trin/pull/465#issuecomment-1507147187 "maintain our own jsonrpc service?" can we close this issue?

**Closed** 2023-04-18 08:28 UTC
